-- H2 test schema (PostgreSQL-compatible mode)
CREATE TABLE IF NOT EXISTS institutes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    code       VARCHAR(20) NOT NULL,
    tagline    VARCHAR(500),
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    code        VARCHAR(100) NOT NULL,
    resource    VARCHAR(50) NOT NULL,
    action      VARCHAR(50) NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institute_id BIGINT NOT NULL,
    name         VARCHAR(100) NOT NULL,
    code         VARCHAR(50) NOT NULL,
    description  VARCHAR(500),
    is_system    BOOLEAN NOT NULL DEFAULT FALSE,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   BIGINT,
    updated_by   BIGINT
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  VARCHAR(36) NOT NULL,
    institute_id          BIGINT NOT NULL,
    username              VARCHAR(100) NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    password_hash         VARCHAR(255) NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100),
    phone                 VARCHAR(20),
    avatar_url            VARCHAR(1000),
    is_active             BOOLEAN NOT NULL DEFAULT TRUE,
    is_email_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at         TIMESTAMP,
    password_changed_at   TIMESTAMP,
    failed_login_attempts INT NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by            BIGINT,
    updated_by            BIGINT,
    deleted_at            TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    token_hash    VARCHAR(255) NOT NULL,
    expires_at    TIMESTAMP NOT NULL,
    is_revoked    BOOLEAN NOT NULL DEFAULT FALSE,
    revoked_at    TIMESTAMP,
    revoke_reason VARCHAR(100),
    ip_address    VARCHAR(45),
    user_agent    VARCHAR(500),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sequence_counters (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institute_id   BIGINT NOT NULL,
    sequence_type  VARCHAR(50) NOT NULL,
    year           INT NOT NULL,
    current_value  BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS students (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  VARCHAR(36) NOT NULL,
    institute_id          BIGINT NOT NULL,
    student_number        VARCHAR(30) NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100),
    email                 VARCHAR(255),
    phone                 VARCHAR(20) NOT NULL,
    whatsapp_number       VARCHAR(20),
    date_of_birth         DATE,
    gender                VARCHAR(10),
    address               TEXT,
    city                  VARCHAR(100),
    state                 VARCHAR(100),
    pincode               VARCHAR(10),
    photo_url             VARCHAR(1000),
    parent_name           VARCHAR(200),
    parent_phone          VARCHAR(20),
    parent_email          VARCHAR(255),
    emergency_contact     VARCHAR(20),
    highest_qualification VARCHAR(200),
    school_college_name   VARCHAR(300),
    status                VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    lead_id               BIGINT,
    notes                 TEXT,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by            BIGINT,
    updated_by            BIGINT,
    deleted_at            TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student_documents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL,
    admission_id    BIGINT,
    document_type   VARCHAR(50) NOT NULL,
    file_name       VARCHAR(500) NOT NULL,
    file_url        VARCHAR(1000) NOT NULL,
    file_size_bytes BIGINT,
    mime_type       VARCHAR(100),
    is_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    verified_by     BIGINT,
    verified_at     TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_by      BIGINT,
    deleted_at      TIMESTAMP
);
